#!/usr/bin/env python3
"""
独立内核包（.zbk）打包 / 校验工具。

用法：
    # 打包一个已准备好的内核目录（目录内需含 kernel.json）
    python tool/pack_kernel.py <内核目录> [输出.zbk]

    # 生成一个可直接安装的示例内核包（用于联调安装流程）
    python tool/pack_kernel.py --demo [输出.zbk]

内核包目录结构（.zbk 本质是 zip，路径以本目录为根）：
    kernel.json                必需：内核清单
    bin/windows/kernel.dll     按平台/ABI 存放的原生库
    bin/linux/libkernel.so
    bin/android/arm64-v8a/libkernel.so
    runtime/                   可选：WebView2 Fixed Version 类运行时目录
"""
import json
import os
import re
import sys
import zipfile

# 与 Dart 侧 KernelManifest / KernelPackage 保持一致的校验规则
SUPPORTED_TYPES = ("ffi", "webview2_fixed")
SUPPORTED_ABI = 1
ID_RE = re.compile(r"^[a-z0-9_]+(\.[a-z0-9_]+)+$")
MANIFEST_ENTRY = "kernel.json"
SKIP_FILES = (".DS_Store",)
SKIP_SUFFIX = ("~",)
SKIP_DIRS = (".git", "__MACOSX")

DEMO_MANIFEST = {
    "manifest_version": 1,
    "id": "com.example.kernel.demo",
    "name": "示例独立内核包",
    "display_name": "示例内核（Demo）",
    "version": "1.0.0",
    "engine": "custom",
    "type": "ffi",
    "abi_version": 1,
    "description": "用于验证内核安装/切换流程的占位内核包，不含真实渲染实现。",
    "engine_version": "demo-1.0.0",
    "capabilities": ["loadUrl", "evaluateJs", "userScripts", "multiTab", "download"],
    "libraries": {
        "windows": "bin/windows/kernel.dll",
        "linux": "bin/linux/libkernel.so",
        "android": {
            "arm64-v8a": "bin/android/arm64-v8a/libkernel.so",
            "armeabi-v7a": "bin/android/armeabi-v7a/libkernel.so",
            "x86_64": "bin/android/x86_64/libkernel.so",
        },
    },
}


def validate(manifest):
    """返回错误字符串列表（空表示合法）。"""
    errors = []

    def req(key):
        v = manifest.get(key)
        if not isinstance(v, str) or not v.strip():
            errors.append(f'字段 "{key}" 缺失或不是非空字符串')
            return ""
        return v.strip()

    mid = req("id")
    req("name")
    req("version")

    if not isinstance(manifest.get("manifest_version"), int):
        errors.append('字段 "manifest_version" 必须是整数')
    if mid and not ID_RE.match(mid):
        errors.append('"id" 必须采用反向域名格式，如 com.example.kernel.chromium')

    mtype = str(manifest.get("type", "ffi")).strip()
    if mtype not in SUPPORTED_TYPES:
        errors.append(f'"type" 必须是 {"/".join(SUPPORTED_TYPES)} 之一，当前为 "{mtype}"')

    abi = manifest.get("abi_version", 1)
    if not isinstance(abi, int):
        errors.append('字段 "abi_version" 必须是整数')
    elif mtype == "ffi" and abi != SUPPORTED_ABI:
        errors.append(f'FFI 内核 ABI 版本需为 {SUPPORTED_ABI}，当前为 {abi}')

    libs = manifest.get("libraries")
    if libs is not None and not isinstance(libs, dict):
        errors.append('字段 "libraries" 必须是对象')
    runtime = manifest.get("runtime_dir")
    if not libs and not (mtype == "webview2_fixed" and runtime):
        errors.append("清单未声明任何平台产物（libraries / runtime_dir 均为空）")

    caps = manifest.get("capabilities")
    if caps is not None and not isinstance(caps, list):
        errors.append('字段 "capabilities" 必须是数组')

    return errors


def iter_files(src):
    for root, dirs, files in os.walk(src):
        dirs[:] = [d for d in dirs if d not in SKIP_DIRS]
        for f in files:
            if f in SKIP_FILES or f.endswith(SKIP_SUFFIX):
                continue
            full = os.path.join(root, f)
            arc = os.path.relpath(full, src).replace(os.sep, "/")
            yield full, arc


def write_zip(src, out):
    count = 0
    with zipfile.ZipFile(out, "w", zipfile.ZIP_DEFLATED) as z:
        for full, arc in iter_files(src):
            z.write(full, arc)
            count += 1
    return count


def pack_dir(src, out):
    manifest_path = os.path.join(src, MANIFEST_ENTRY)
    if not os.path.isfile(manifest_path):
        print(f"目录内未找到 {MANIFEST_ENTRY}：{src}")
        return 1

    try:
        with open(manifest_path, "r", encoding="utf-8") as fh:
            manifest = json.load(fh)
    except (OSError, ValueError) as exc:
        print(f"{MANIFEST_ENTRY} 解析失败：{exc}")
        return 1

    errors = validate(manifest)
    if errors:
        print("内核清单校验失败：")
        for e in errors:
            print(f"  - {e}")
        return 1

    count = write_zip(src, out)
    print(f"打包完成：{out}（{count} 个文件）")
    print(f"内核 id：{manifest['id']} · 类型：{manifest.get('type', 'ffi')}")
    return 0


def pack_demo(out):
    import tempfile

    with tempfile.TemporaryDirectory() as tmp:
        with open(os.path.join(tmp, MANIFEST_ENTRY), "w", encoding="utf-8") as fh:
            json.dump(DEMO_MANIFEST, fh, ensure_ascii=False, indent=2)

        # 占位原生库（内容为说明文本，仅用于验证安装与探测流程）
        placeholder = (
            "This is a placeholder native library generated by pack_kernel.py --demo.\n"
            "Replace it with a real kernel implementation before production use.\n"
        )
        for platform, rel in (
            ("windows", "bin/windows/kernel.dll"),
            ("linux", "bin/linux/libkernel.so"),
            ("android/arm64-v8a", "bin/android/arm64-v8a/libkernel.so"),
            ("android/armeabi-v7a", "bin/android/armeabi-v7a/libkernel.so"),
            ("android/x86_64", "bin/android/x86_64/libkernel.so"),
        ):
            path = os.path.join(tmp, rel.replace("/", os.sep))
            os.makedirs(os.path.dirname(path), exist_ok=True)
            with open(path, "w", encoding="utf-8") as fh:
                fh.write(f"# {platform}\n{placeholder}")

        with open(os.path.join(tmp, "README.md"), "w", encoding="utf-8") as fh:
            fh.write(
                "# 示例独立内核包\n\n"
                "本包由 `tool/pack_kernel.py --demo` 生成，仅用于验证「内核管理」页的\n"
                "安装 / 探测 / 切换 / 卸载流程，不包含真实的渲染实现。\n"
            )

        count = write_zip(tmp, out)

    print(f"示例内核包已生成：{out}（{count} 个文件）")
    print("可在应用内「设置 → 内核管理 → 安装」选择该文件进行验证。")
    return 0


def main():
    args = sys.argv[1:]
    if not args:
        print(__doc__.strip())
        return 1

    if args[0] in ("-h", "--help"):
        print(__doc__.strip())
        return 0

    if args[0] == "--demo":
        out = args[1] if len(args) > 1 else "zip-browser-kernel-demo.zbk"
        return pack_demo(out)

    src = os.path.abspath(args[0])
    if not os.path.isdir(src):
        print(f"目录不存在：{src}")
        return 1

    out = args[1] if len(args) > 1 else os.path.basename(src.rstrip(os.sep)) + ".zbk"
    return pack_dir(src, out)


if __name__ == "__main__":
    sys.exit(main())
